package com.boss.demo.db.mapper;

import com.boss.demo.db.model.Details;
import com.boss.demo.db.sqlprovider.DetailsSqlProvider;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Jul 20 23:09:11 CST 2020
     */
    @Delete({
        "delete from details",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Jul 20 23:09:11 CST 2020
     */
    @Insert({
        "insert into details (id, name, ",
        "spec, num, detailId)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{spec,jdbcType=VARCHAR}, #{num,jdbcType=INTEGER}, #{detailid,jdbcType=INTEGER})"
    })
    int insert(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Jul 20 23:09:11 CST 2020
     */
    @InsertProvider(type= DetailsSqlProvider.class, method="insertSelective")
    int insertSelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Jul 20 23:09:11 CST 2020
     */
    @Select({
        "select",
        "id, name, spec, num, detailId",
        "from details",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="spec", property="spec", jdbcType=JdbcType.VARCHAR),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="detailId", property="detailid", jdbcType=JdbcType.INTEGER)
    })
    Details selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Jul 20 23:09:11 CST 2020
     */
    @UpdateProvider(type=DetailsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Jul 20 23:09:11 CST 2020
     */
    @Update({
        "update details",
        "set name = #{name,jdbcType=VARCHAR},",
          "spec = #{spec,jdbcType=VARCHAR},",
          "num = #{num,jdbcType=INTEGER},",
          "detailId = #{detailid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Details record);
}